source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

inhibit_all_warnings!

target :GKiOSNovel  do
    #-------- 开源第三方库 -----
    pod 'AppBaseCategory'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'SDWebImage'
    pod 'EAIntroView'
    pod 'MMPopupView', :git => 'https://github.com/CoderLT/MMPopupView.git'
    pod 'MJRefresh', :git => 'https://github.com/CoderLT/MJRefresh.git'
    pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
    pod 'VTMagic',:git => 'https://github.com/tianya2416/VTMagicMacro.git'
    pod 'DZNEmptyDataSet'
    pod 'KVOController'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'HHTransition'
    pod 'SDCycleScrollView'
    pod 'KLRecycleScrollView'
end

