
source      'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

#use_frameworks!

inhibit_all_warnings!

target :GKiOSNovel  do
    #-------- 开源第三方库 -----
    pod 'ATKit_ObjectC',:git => 'https://github.com/tianya2416/ATKit_ObjectC.git'
    pod 'ATRefresh_ObjectC',:git => 'https://github.com/tianya2416/ATRefresh_ObjectC.git'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'SDWebImage'
    pod 'EAIntroView'
    pod 'MMPopupView', :git => 'https://github.com/CoderLT/MMPopupView.git'
    pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
    pod 'VTMagic',:git => 'https://github.com/tianya2416/VTMagicMacro.git'
    pod 'UICollectionView-ARDynamicHeightLayoutCell', :git => 'https://github.com/tianya2416/FDCacheHeightLayoutCell.git'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'SDCycleScrollView'
    pod 'KLRecycleScrollView'
    pod 'HWPanModal'
#---------- 分享SDK -------
    pod 'mob_sharesdk'
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat’
end

